dist: trusty
sudo: required
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
os:
- linux

before_install:
- echo "$TRAVIS_BRANCH"
- echo "$TRAVIS_PULL_REQUEST"

script:
- yarn install
- yarn test
